name: beckend-ci-workflow

on:
  workflow_dispatch:
  pull_request:
    types: [edited]
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pip install flake8

      - run: pipenv run lint
  
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pip install flake8

      - run: |
          pipenv install pytest
          pipenv run test

  build:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build --tag=mp-backend:latest .
        
